
const express = require('express')
const router = express.Router()
const register = require("../auth/registerRoute")
const login = require('../auth/Login')
const VendorProducts = require('../Products/Product_manegement')
const UpdateRequestByAdmin = require('../Admin/Product_management')
const GetAllProduct = require('../routes/GetAllProducts')
const CreateCoupon = require('../Admin/CreateCoupon')
const CraeateCategory = require('../Categories/CreateCategory')
const Subcategorory = require('../Categories/SubCategories')
const Orders = require('../Orders/PlaceOrder')
const CancelOrders = require('../Orders/CancelOrder')
const AddAddress = require('./AddAddress')
const UpdateOrderStatus = require('../Admin/OrderStatusUpdate')
const InventryManage = require('../Admin/Inventory_Management')
const Payment = require('../routes/Payment')
const AddToCart = require('../routes/AddToCart')
const AdminrDashboradRoutes = require('../Admin/Admin_Dashboard_Routes')
const OrderDetails = require('../routes/OrderDetails') 
const userDetails = require('../routes/userDetails')
// const LowstockAlert = require('../utils/SendLowStockAlert')
/////////////////////////////////////////////
router.use('/',register)
router.use('/',login)
router.use('/',VendorProducts)
router.use('/',UpdateRequestByAdmin)
router.use('/',GetAllProduct)
router.use('/',CreateCoupon)
router.use('/',CraeateCategory)
router.use('/',Subcategorory)
router.use('/',Orders)
router.use('/',AddAddress)
router.use('/',CancelOrders)
router.use('/',UpdateOrderStatus)
router.use('/',InventryManage)
router.use('/',Payment)
router.use('/',AddToCart)
router.use('/',AdminrDashboradRoutes)
router.use('/',OrderDetails)
router.use('/',userDetails)
// router.use('/',LowstockAlert)
module.exports = router